/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    MovieButton: typeof import('primevue/button')['default']
    MovieCard: typeof import('primevue/card')['default']
    MovieImage: typeof import('primevue/image')['default']
    MovieTag: typeof import('primevue/tag')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
